import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import ConvexClientProvider from "./ConvexClientProvider";
import SessionProvider from "~/components/SessionProvider";
import { getServerSession } from "next-auth";
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="min-h-screen">
          <ConvexClientProvider>
            <SessionProvider session={session}>{children}</SessionProvider>
          </ConvexClientProvider>
        </div>
      </body>
    </html>
  );
}
